includes("../src/xmake.lua")
add_rules("mode.debug","mode.release")
add_rules("plugin.vsxmake.autoupdate")
add_requires("glad")
add_requires("libigl >= 2.4.0",{configs = {imgui=true}})
target("libshell_example")
    set_kind("binary")
    add_files("*.cpp")
    add_packages("libigl",{public=true})
    add_packages("glad")
    add_deps("libshell")