add_requires("eigen >=3.4.0")
add_rules("mode.debug","mode.release")
add_rules("plugin.vsxmake.autoupdate")
add_defines("EIGEN_STRONG_INLINE=inline")
target("libshell")
    set_kind("static")
    add_headerfiles("./include/*.h")
    add_includedirs("./include/",{public=true})
    add_files("./src/*.cpp","./src/MaterialModel/*.cpp","./src/SecondFundamentalForm/*.cpp")
    add_packages("eigen",{public=false})